### ISSUE TITLE
Does not work on node < 4.5.0

### ISSUE THREAD

**Issue by alasdairhurst** [request/request#2781] opened 2017-09-22 17:17 UTC
### Summary
Your package.json specifies a node version of >=4 however one of your dependencies has a version of >4.5.0 (hawk)
https://github.com/hueniverse/hawk/blob/master/package.json

### Simplest Example to Reproduce

```
var request = require("request")
```

### Current Behavior
This causes the following error when requiring request on older node versions such as 4.2.0
```
Uncaught Exception Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at require (/Users/username/app/node_modules/hawk/lib/index.js:1:258)
    at Object.<anonymous> (/Users/username/app/node_modules/hawk/lib/index.js:5:33)
```

### Possible Solution
Either bump the minimum supported node version, or get hawk to loosen up.

### Your Environment

| software         | version
| ---------------- | -------
| request          | 2.82.1
| node             | 4.2.0
| npm              | 2.14
| Operating System | Ubuntu

**Comment by mikeal** [comment] 2017-09-25 17:40
Closing as duplicate of several other issues.

**Closed by mikeal** 2017-09-25 17:40 UTC

**Comment by alasdairhurst** [comment] 2017-09-25 23:51
@mikeal I can't seem to find these duplicate issues. Could you please link them so we can track them easier? (and if someone finds this issue through a search)

**Comment by mikeal** [comment] 2017-09-26 00:29
They are all closed. Look at the recent closed issues. We cut support for EOL Node.js versions almost a year ago.
