### ISSUE TITLE
localAddress on redirect

### ISSUE THREAD

**Issue by nytr0gen** [request/request#1432] opened 2015-02-17 17:22 UTC
When request performs a redirect with certain opts, it doesn't copy the old opts (I've seen it happen just with localAddress) to the new request that is performing the redirect. Any tips on how to fix it?

**Comment by 0x4139** [comment] 2015-02-18 08:39
I can confirm that this is an issue :)

**Comment by nylen** [comment] 2015-02-19 05:14
Patch with tests welcome.

**Comment by joshux** [comment] 2015-07-28 09:39
Is this issue fixed in #1437 ?

**Comment by simov** [comment] 2015-07-29 14:00
Yes, seems to be fixed here https://github.com/request/request/pull/1460

@joshux do you have any issues with it?

**Closed by simov** 2015-07-29 14:00 UTC

**Comment by joshux** [comment] 2015-07-29 14:46
I'm just new, trying to find a bug to fix :)

2015-07-29 16:00 GMT+02:00 simo <notifications@github.com>:
