### ISSUE TITLE
send Post : Maximum call stack size exceeded

### ISSUE THREAD

**Issue by throrin19** [request/request#1358] opened 2015-01-15 16:15 UTC
Hi, I've a serious bug with Request.js,

If I try to post an array, i have a node.js crash (without stacktrace). The console just return this : 

```
Maximum call stack size exceeded
```

I try to search the problem with node-inspector and, the error is on this line : 

require.js line 1415
```
self.body = (typeof form === 'string') ? form.toString('utf8') : self.qsLib.stringify(form).toString('utf8')
```

This is my POST Data : 

```
{
  field1 : true,
  field2 : false,
  field3 : true,
  names : [
    {
      'val' : 'value fr',
      'lang' : 'fr' 
    }, ...
  ]
```

And this is my require call : 

```
request.post({
        url     : this.url + params.url,
        form    : params.post
    }, callback);
```

Edit : 

I try to change the `form` attribute by `formData` and i have this error now : 

```
TypeError: Object #<Object> has no method 'on'
    at Function.DelayedStream.create (/home/******/public_html/******/node_modules/request/node_modules/combined-stream/node_modules/delayed-stream/lib/delayed_stream.js:33:10)
    at FormData.CombinedStream.append (/home/******/public_html/******/node_modules/request/node_modules/combined-stream/lib/combined_stream.js:43:37)
    at FormData.append (/home/******/public_html/******/node_modules/request/node_modules/form-data/lib/form_data.js:43:3)
    at appendFormValue (/home/******/public_html/******/node_modules/request/request.js:496:21)
    at Request.init (/home/******r/public_html/******/node_modules/request/request.js:507:11)
    at new Request (/home/******/public_html/goomeoeventsapi/node_modules/request/request.js:283:8)
    at request (/home/webuser/public_html/goomeoeventsapi/node_modules/request/index.js:50:10)
    at Function.request.post (/home/******/public_html/******/node_modules/request/index.js:80:27)
    at post (/home/******/public_html/******/app/services/v1.2/v3_service.js:24:13)
```

**Comment by nylen** [comment] 2015-01-16 16:57
I can't reproduce this with the snippet you posted:

```js
var querystring = require('querystring'),
    qs          = require('qs');

var data = {
    field1 : true,
    field2 : false,
    field3 : true,
    names  : [
        {
            'val'  : 'value fr',
            'lang' : 'fr'
        }
    ]
};

console.log(querystring.stringify(data));
console.log(qs.stringify(data));
```

It looks to be a bug with [`qs`](https://github.com/hapijs/qs) though.  Make sure you don't have any circular references in your data and/or try adding `useQuerystring : true` to your options.

If that doesn't work then post a snippet like the above that reproduces the behavior.

**Comment by nylen** [comment] 2015-01-20 16:30
closing, let us know if this is still an issue.

**Closed by nylen** 2015-01-20 16:30 UTC

**Comment by throrin19** [comment] 2015-01-21 07:41
Hi, sorry for the delay. The problem is in this package : `form-data`.

If I try to pass complex object (like my post), form Data dosn't know how transform this object on Form-data params (it's the same problem with `qs`).

To resolve this bug, i transform my complex object into simple key:value object and it works fine : 

```
{
  field1 : true,
  field2 : false,
  field3 : true,
  "names[0][val] :  'value fr',
  "names[0][lang]" : "fr"
}
```

**Comment by simov** [comment] 2015-01-21 08:30
@throrin19 I don't think `form-data` supports array body type in the first place https://github.com/felixge/node-form-data/blob/master/lib/form_data.js#L35
