### ISSUE TITLE
POST 301 redirects don't respect "agent" property

### ISSUE THREAD

**Issue by jrasanen** [request/request#1304] opened 2014-12-04 17:36 UTC
When POST returns 301, the following GET isn't using the same agent setting.

```js
    var options = {
        url: 'http://website/',
        method: 'POST',
        headers: headers,
        followAllRedirects: true,
        agent: new Socks5ClientHttpAgent({socksHost: '127.0.0.1', socksPort: 9050}),
        form: {
          ...
        }
    }
    // POST returns 301 /index.php
    request.post(options, function (err, httpResponse, body) {...});
```

With this example POST goes through TOR but the following GET doesn't.

**Comment by polkovnikov-ph** [comment] 2015-01-26 18:04
Have anybody tried fixing that?

**Comment by mattcg** [comment] 2015-01-26 19:07
I've submitted a pull request that fixes this issue.

**Comment by mattcg** [comment] 2015-01-26 20:52
@nylen I've tracked down the original issue: https://github.com/request/request/pull/15.

One possible solution is to pass an agent factory, either as an `agentFactory` option or by checking whether `typeof self.agent == 'function'` and if so consider it to be a factory.

**Comment by nylen** [comment] 2015-01-26 21:07
:+1: nice catch.  I'd take a PR for that (with appropriate tests and docs).  I'd prefer to make it explicit with `agentFactory`.

**Comment by mattcg** [comment] 2015-02-25 19:40
@nylen there is actually no need for a new option. I realised that the `agentClass` and `agentOptions` options already provide what we need.

The issue is that when `request.init()` is called on [line 141 of redirect.js](https://github.com/request/request/blob/41319044e602af69cdfad9a92dc0c4fd4d30db0a/lib/redirect.js#L141) the options aren't passed and `self.agentClass` is reassigned to the default.

A fix for this that would have no side effects would be to change [line 589](https://github.com/request/request/blob/41319044e602af69cdfad9a92dc0c4fd4d30db0a/request.js#L589) to `if (!self.agent && !self.agentClass) {`.

**Comment by simov** [comment] 2015-02-26 07:52
Hi @mattcg can you submit a PR for that change, and add some tests for it?

**Comment by mattcg** [comment] 2015-02-26 10:30
@simov see pull request #1451.

**Comment by Freyert** [comment] 2015-09-08 19:04
So, this looks to be also connected with issue #1502 or at least stem from a similar issue. It seems like it might be good for `Redirects` to respect the options set in the original request in general. I am probably oversimplifying a bit here though.

In my case the issue is that I've set `request.defaults` with a cookiejar and the `Redirects` do not use said cookie jar.

**Closed** 2015-10-22 13:46 UTC
