### ISSUE TITLE
Bug when setting up the body via the form method

### ISSUE THREAD

**Issue by LucasSeveryn** [request/request#1630] opened 2015-06-05 09:02 UTC
Example:

    fd={'key A to B':'value'}
    request.post('http://service.com/upload').form(fd)

will not encode the spaces correctly and therefore the response will not be successful.

**Comment by simov** [comment] 2015-06-05 10:13
The problem is not with the encoding, but rather with the usage of the `form` method.

Notice that the bottom request doesn't have form parameters and a body - http://requestb.in/1emxna81?inspect. This is the result from using the `form` method:

```js
request.post('http://requestb.in/1emxna81')
      .form({'key A to B':'value'})
```

I'll investigate that further, in the meantime you can just pass the parameters through the `form` option

```js
request.post('http://requestb.in/1emxna81',
      {form:{'key A to B':'value'}})
```

**Comment by simov** [comment] 2015-06-23 08:43
@LucasSeveryn I just pushed the fix here https://github.com/request/request/pull/1656 can you pull it and check if it works for you?

**Closed** 2015-06-26 07:35 UTC
