### ISSUE TITLE
[Error: socket hang up] code : 'ECONNRESET' }

### ISSUE THREAD

**Issue by JohnJeong123** [request/request#1544] opened 2015-04-14 01:45 UTC
Below code is my service application test code
but I faced fatal error. [Error: socket hang up] code : 'ECONNRESET' }
I want to know everyones commnets.

```js
var request = require('request'),
        fs = require('fs'),
        log4js = require('log4js'),
        logger = log4js.getLogger('xls2json_ranger'),
        sendEmail = require('./mailconfig.js').sendEmail;

logger.setLevel('INFO');

var formData = {
        custom_file:{
                value : fs.createReadStream('./test.xlsx'),
                options: {
                        filename: 'test.xlsx'
                }
        }
};

var testInterval = setInterval(function(){
        var date = new Date();
        logger.info(date.getSeconds());

        if(date.getSeconds()%10===0){
                checkServerStatus();
        }
},1000);


var options = {
        url:'http://192.168.10.240:4000/upload/',
        headers: {
                'origin':'blabla'
        },
        formData:formData,
        pool:false
};

function checkServerStatus(){

        request.post(options, function optionalCallback(err, httpResponse, body){

                if (err) {
                        sendEmail();
                        return logger.error(err);
                }

                if(IsJsonString(body) == false){
                        sendEmail();
                        return logger.error('result is not json body');;
                } else {
                        logger.info("xlsx test complete");
                        return;
                }
        });
}


function IsJsonString(str) {
    try {
        return JSON.parse(str);
    } catch (e) {
        return false;
    }
```

**Comment by simov** [comment] 2015-04-24 16:02
@JohnJeong123 did you managed to get it working? Most probably you have misconfigured your request. For example `custom_file` refers to the form field name that the server expects, this key name is used only for explanation in the readme.

**Comment by simonprev** [comment] 2015-09-09 18:44
I also have this behavior when I use `formData` option on a request. It’s not even a file, just the simplest option `{formData: { filename: "test.jpg" }}` just hang until the `'ECONNRESET'` error occurs.

I interact with the **AdGear** API which uses HTTP Digest Auth (I don’t know if it can have an influence in the issue)

```js
request.post({
  url:'http://api.admin.adgear.com/uploads.xml',
  formData: {filename: "test.jpg"},
  auth: {
    user: 'user',
    pass: 'password',
    sendImmediately: false
  }
},
function optionalCallback(err, httpResponse, body) {
  if (err) {
    return console.error('upload failed:', err);
  }
  console.log('Upload successful!  Server responded with:', body);
});
```

If I don’t include the `formData` parameter, I have the correct error from **AdGear** requesting a valid filename.

I know this issue is old, but I could use some support because now my solution is to make the call using `curl` inside my nodejs app :smile:

Thank you!

**Comment by simov** [comment] 2015-09-14 17:34
Hey, @simonprev, try this:

```js
request.post({
  url:'http://api.admin.adgear.com/uploads.xml',
  formData: {Filedata: fs.createReadStream('file.jpg')},
  auth: {
    user: 'user',
    pass: 'password',
    sendImmediately: false
  }
},
function optionalCallback(err, httpResponse, body) {
  if (err) {
    return console.error('upload failed:', err);
  }
  console.log('Upload successful!  Server responded with:', body);
});
```

> [docs](https://adgear.atlassian.net/wiki/display/adgear/Creating+an+Image+Ad+via+API) for reference

I'm closing this, let me know if it works for you. Also feel free to open another issue.

**Closed by simov** 2015-09-14 17:34 UTC

**Comment by simonprev** [comment] 2015-09-14 18:16
Here you go: https://github.com/request/request/issues/1769

I hope you can reproduce the issue on your side...
