### ISSUE TITLE
module not find

### ISSUE THREAD

**Issue by sunriseshow** [request/request#2532] opened 2017-02-09 04:01 UTC
net ,fs, tls  not found

![image](https://cloud.githubusercontent.com/assets/8856011/22768812/6ca15722-eebf-11e6-83a1-bccce15cfb50.png)

why????????

**Comment by crostine** [comment] 2017-02-09 10:30
it would help the world and yourself if you post a step by step guide to reproduce, or even the context at which this occurs.

**Comment by fabienheureux** [comment] 2017-02-18 11:54
Maybe dig this issue could help you (I encounter the same on using webpack)
https://github.com/request/request/issues/1529

**Comment by FredKSchott** [comment] 2017-02-19 22:29
Closing as duplicate of #1529
(If you believe that this isn't a duplicate, please create a new issue with more information.)

**Closed by FredKSchott** 2017-02-19 22:29 UTC
